version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=Test@213
    ports:
      - "8086:8080"
    command: start-dev
    depends_on:
      - postgres
      - mailhog
    networks:
      app-network:
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    environment:
      - MH_STORAGE=maildir # Persist emails
    volumes:
      - mailhog-data:/maildir
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      app-network:
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Test@213
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      app-network:
    restart: unless-stopped


#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"   # RabbitMQ (AMQP) port
#      - "15672:15672" # Management UI
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mailhog-data:
  postgres-data:
  rabbitmq_data:

networks:
  app-network:
    name: app-network
    driver: bridge