spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 60000

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
            keycloak:
                issuer-uri: http://localhost:8080/realms/master
                client-id: zylo-web
                scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8080
  realm: master
  admin-username: sankar@gmail.com
  admin-password: mni8gthu9XretHJb2YS4RUQpayF6098p
  admin-client-id: zylo-web

server:
  port: 8081

#debug: true
#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    com.zylo.authservice: DEBUG
#    org.keycloak: DEBUG
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG